//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MV.Prometric.EntityModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vehicle
    {
        public long Id { get; set; }
        public string ModelName { get; set; }
        public string Color { get; set; }
        public decimal MpgValue { get; set; }
    }
}
